=== crazywm/crazys-wm-mod/Resources/Data/Jobs/job.dtd
<!ELEMENT Job (Description, Performance, Modifiers?, Gains, Config, Messages?)>
<!ATTLIST Job ShortName CDATA #REQUIRED>

<!ELEMENT Description (#PCDATA)>
<!ELEMENT Config ANY>

<!ELEMENT Performance (Factor|Trait|Mod)*>
<!ATTLIST Performance Modifier CDATA #IMPLIED>
<!ELEMENT Factor EMPTY>
<!ATTLIST Factor Skill CDATA #IMPLIED Stat CDATA #IMPLIED Weight CDATA #IMPLIED Min CDATA #IMPLIED Max CDATA #IMPLIED>

<!ELEMENT Gains (GainTrait|LoseTrait|Skill|Stat)*>
<!ATTLIST Gains XP CDATA #IMPLIED Skill CDATA #IMPLIED>
<!ELEMENT GainTrait (#PCDATA)>
<!ATTLIST GainTrait Trait CDATA #REQUIRED Threshold CDATA #REQUIRED Action CDATA #REQUIRED Event CDATA #IMPLIED Chance CDATA #IMPLIED MinPerformance CDATA #IMPLIED>
<!ELEMENT LoseTrait (#PCDATA)>
<!ATTLIST LoseTrait Trait CDATA #REQUIRED Threshold CDATA #REQUIRED Action CDATA #REQUIRED Event CDATA #IMPLIED Chance CDATA #IMPLIED MinPerformance CDATA #IMPLIED>
<!ELEMENT Skill (EMPTY)>
<!ATTLIST Skill Name CDATA #REQUIRED Weight CDATA Min CDATA Max CDATA>
<!ELEMENT Stat (EMPTY)>
<!ATTLIST Stat Name CDATA #REQUIRED Weight CDATA Min CDATA Max CDATA>

<!ELEMENT Messages (Message|Include)*)>
<!ELEMENT Message ((Text|Group)+)>
<!ATTLIST Message Name CDATA #REQUIRED>
<!ELEMENT Text (#PCDATA)>
<!ATTLIST Text Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>
<!ELEMENT Group ((Text|Group)+)>
<!ATTLIST Group Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>

<!ELEMENT Modifiers (Modifier)*>
<!ELEMENT Modifier (Trait)*>
<!ATTLIST Modifier Name CDATA #REQUIRED>
<!ELEMENT Trait (EMPTY)*>
<!ATTLIST Trait Name CDATA #REQUIRED Value CDATA #REQUIRED>

<!ELEMENT Mod (#PCDATA)>
<!ATTLIST Mod Weight CDATA #IMPLIED>

<!ELEMENT Include (#PCDATA)>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/FilmStrip.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FStp">
    <Description>
        She will perform in a strip tease scene.
    </Description>

    <Performance>
        <Factor Stat="Charisma" Weight="1"/>
        <Factor Stat="Beauty" Weight="1"/>
        <Factor Skill="Performance" Weight="1"/>
        <Factor Skill="Strip" Weight="2"/>
        <Mod>work.pornstar</Mod>
        <Trait Name="Clumsy" Value="-15" />
        <Trait Name="Manly" Value="-10" />
    </Performance>

    <Gains XP="15" Skill="3">
        <Skill Name="Performance" Weight="2" />
        <Skill Name="Strip" Weight="1" />
        <Stat Name="Charisma" Weight="1" Max="50"/>
        <GainTrait Trait="Sexy Air" Threshold="80" Action="WORKSTRIP" MinPerformance="150" Chance="25">
            ${name} has been stripping for so long, when she walks, it seems her clothes just want to fall off.
        </GainTrait>

        <LoseTrait Trait="Chaste" Threshold="20" Action="PORNSTAR">
            She has been filmed having sex so often that she is no longer Chaste.
        </LoseTrait>
    </Gains>

    <Config PrimaryAction="PORNSTAR" SecondaryAction="WORKSTRIP">
        <LustInfluence Amount="5" SkillMin="5" BaseValue="5" Skill="Strip" />
    </Config>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as an actress filming strip tease scenes.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to strip on film today.</Text>
        </Message>

        <Message Name="work.perfect">
            <Text>${name} is so in love with her body, she strips erotically making the best Perfect Art.</Text>
        </Message>
        <Message Name="work.great">
            <Text>${name} greatly teased the camera by slowly stripping of her clothes with many kisses.</Text>
        </Message>
        <Message Name="work.good">
            <Text>${name} was good with the chosen music to strip with. She even sang with the songs.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>${name} did ok today. She was distracted by the other actions around her.</Text>
        </Message>
        <Message Name="work.bad">
            <Text>${name} quickly striped off her clothes, acting like this was her times being processed at the jail.</Text>
            <Text Condition="Clumsy|Dojikko">
                ${name} began to take off her clothes slowly. Not because she was particularly sensual about it, it just
                took her three tries to open her bra. "Cut!" comes the instruction from the director. "Let's try this again."

                This time, everything seems to go smoothly, until her heels get entangled in her panties and she falls over.
                The director sighs, looking at ${name}'s bloody nose. "I guess we need to work with the footage we have now."
            </Text>
        </Message>
        <Message Name="work.worst">
            <Text>${name} is the worst stripper you have EVER seen. Way to shy to even look up and she blushed the entire remakes.</Text>
            <Text Condition="Chaste|Shy|Nervous">
                ${name} looks so uncomfortable when the director orders her to take her clothes off that you imagine
                even blind people would be turned off by this scene.
            </Text>
        </Message>

        <Message Name="post-work-event">
            <Text Condition="Performance < 100 ^ stat:Beauty < 33">
                At the end of the filming, the director looks at you apologetically. "I've tried", she says, "but
                I think ${name} is just too ugly for this"
            </Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/BrothelStripper.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="BStp">
    <Description>
        She will strip for the customers.
    </Description>

    <Performance>
        <Factor Stat="Beauty" Weight="2"/>
        <Factor Stat="Charisma" Weight="2"/>
        <Factor Skill="Performance" Weight="1"/>
        <Factor Skill="Strip" Weight="2"/>

        <Mod>work.stripper</Mod>

        <!--
        The original code had a fame bonus and a pregnancy malus
        -->
    </Performance>

    <Config>
        <WageFunction>
            <Point Performance="245" Wages="155" />
            <Point Performance="185" Wages="95" />
            <Point Performance="145" Wages="55" />
            <Point Performance="100" Wages="15" />
            <Point Performance="70" Wages="-5" />
            <Point Performance="0" Wages="-15" />
        </WageFunction>
    </Config>

    <Gains XP="20" Skill="3">
        <LoseTrait Trait="Nervous" Threshold="30" Action="WORKSTRIP">
            ${name} has had so many people see her naked she is no longer nervous about anything.
        </LoseTrait>
        <GainTrait Trait="Sexy Air" Threshold="80" Action="WORKSTRIP">
            ${name} has been stripping and having to be sexy for so long she now reeks of sexyness.
        </GainTrait>
        <GainTrait Trait="Exhibitionist" Threshold="60" Action="WORKSTRIP">
            ${name} has been stripping for so long she loves to be naked now.
        </GainTrait>
        <Skill Name="Performance" Weight="2" />
        <Skill Name="Strip" Weight="2" />
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} was stripping in the brothel.</Text>
        </Message>
        <Message Name="refuse">
            <Text>"${name} refused to strip for customers in your brothel to${shift}</Text>
        </Message>

        <Message Name="work.perfect">
            She must be the perfect stripper - customers go on and on about her and always come to see her when she works.

            <Text>${name} throws her bra into the crowd causing a fight to erupt over who got to take it home. They just love her.</Text>
            <Text>${name} use of the pole amazes the patrons. They truly have no idea how she does the things she does.</Text>
            <Text>People push and shove to get to the front of the stage for ${name}'s dance set.</Text>
            <Text>Somehow, ${name} managed to be so sexy that you thought you might need to close just to clean up the mess the crowd made.</Text>
            <Text Updates="Tips+=15">
                ${name}'s smile is enough to bring in the tips. You sometimes wonder if she even needs to take her clothes off.
            </Text>
        </Message>

        <Message Name="work.great">
            She's unbelievable at this and is always getting praised by the customers for her work.

            <Text>${name} use of the pole makes every head in the place turn to watch.</Text>
            <Text>${name} throws her bra into the crowd causing an uproar of hooting and screaming. She knows how to drive them crazy.</Text>
            <Text>${name} draws just as many females as males to the club when it's her shift. It seems everyone has noticed her skill.</Text>
            <Text>All male members of ${name}'s audience had trouble standing after she finished her set.</Text>
            <Text>From start to finish, every move ${name} makes practically sweats sexuality.</Text>
        </Message>

        <Message Name="work.good">
            She's good at this job and gets praised by the customers often.
            <Text>${name} can spin on the pole in a way that excites the crowd.</Text>
            <Text>${name}'s sly smile and slow striptease drives the crowd crazy.</Text>
            <Text>Since you let ${name} choose the music she dances to, her erotic dances have improved markedly.</Text>
            <Text>You watched with amusement as members of her audience made a disproportionate number of trips to the bathroom after her performance.</Text>
            <Text Updates="Tips+=10">
                Seeing the large crowd waiting outside, ${name} smirked and slowly walked on stage knowing she was going get good tips today.
            </Text>
        </Message>

        <Message Name="work.ok">
            She made a few mistakes but overall she is okay at this.

            <Text>While she won't win any contests, ${name} isn't a terrible stripper.</Text>
            <Text>${name} is not the best erotic dancer you've ever seen, but the drunks enjoy the eyecandy.</Text>
            <Text>${name}'s striptease draws a decent crowd each night.</Text>
            <Text>${name} is able to use the pole without making any mistakes even if she isn't that great on it.</Text>
            <Text>Somehow, ${name} managed to get a decent amount of tips as she slowly took her clothes of during her set on stage.</Text>
        </Message>

        <Message Name="work.bad">
            She was nervous and made a few mistakes. She isn't that good at this.
            <Text>
                ${name} spun around on the pole too much and got dizzy, causing her to fall off-stage buck-naked into the crowd.
                A lot of hands grabbed onto her and helped her back up... at least, that's what they said they were doing.
            </Text>
            <Text>${name}'s hair got tangled up in her shirt when she tried to take it off, making her reel about the stage like a drunk.</Text>
            <Text>For all the reaction she's getting, you could probably replace ${name} with a simple mannequin.</Text>
            <Text>${name} at least managed to get all her clothes off this time.</Text>
            <Text>${name} isn't qualified as a stripper, which might explain why she couldn't successfully detach her bra on stage.</Text>
        </Message>

        <Message Name="work.worst">
            ${name} was stiff and nervous, constantly making mistakes. She really isn't good at this job.

            <Text>${name} slipped of the pole and fell flat on her ass.</Text>
            <Text>${name}'s hair got tangled up in her shirt when she tried to take it off, making her reel about the stage like a drunk.</Text>
            <Text>Seeing the large crowd waiting outside, ${name}'s nerve broke, and she wouldn't take the stage.</Text>
            <Text>Somehow, ${name} forgot that she was a stripper and finished her set with her clothes still on.</Text>
            <Text>Somehow, ${name} managed to be so unsexy that the audience barely seemed to notice her presence.</Text>
        </Message>

        <Message Name="event.post">
            <Text Condition="stat:Beauty>85" Chance="20" Updates="Tips+=25">
                Stunned by her beauty a customer left her a great tip.
            </Text>
            <Text Condition="Clumsy" Chance="5" Updates="Earnings-=15">
                Her clumsy nature caused her to slide off the pole causing her to have to stop stripping for a few hours.
            </Text>
            <Group Condition="Pessimist" Chance="5">
                <Text Condition="Performance > 120" Updates="Tips+=10">
                    ${name} was in a poor mood so the patrons gave her a bigger tip to try and cheer her up.
                </Text>
                <Text Condition="Performance <= 140" Updates="Tips-=10">
                    Her pessimistic mood depressed the customers making them tip less.
                </Text>
            </Group>
            <Group Condition="Optimist" Chance="5">
                <Text Condition="Performance > 120" Updates="Tips+=10">
                    Her optimistic mood made patrons cheer up increasing the amount they tip.
                </Text>
                <Text Condition="Performance <= 149" Updates="Tips-=10">
                    ${name} was in a cheerful mood but the patrons thought she needed to work more on her services.
                </Text>
            </Group>
            <Group Condition="Great Figure" Chance="20">
                <Text Condition="Performance > 125" Updates="Tips+=15">
                    ${name}'s great figure draws a large crowed to the stage and her skill at stripping makes them pay up to see the show up close.
                </Text>
                <Text Condition="Performance <= 125" Updates="Tips+=5">
                    ${name} has a great figure so she draws a few extra patrons even if she needed to work more on her stripping.
                </Text>
            </Group>
            <Text Priority="-1"/>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/FarmHand.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FHnd">
    <Description>
        She will maintain the farm.
    </Description>

    <Performance>
        <Factor Skill="Service" Weight="3"/>
        <Factor Stat="Morality" Weight="1"/>
        <Factor Stat="Obedience" Weight="1"/>
        <Factor Stat="Agility" Weight="1"/>

        <Mod>work.cleaning</Mod>
    </Performance>

    <Messages>
        <Message Name="work">
            <Text>${name} worked cleaning and repairing the farm.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work on the farm during the ${shift} shift.</Text>
        </Message>
        <Message Name="shift.bad">
            <Text>She spilled a bucket of something unpleasant all over herself.</Text>
            <Text>She did not like working on the farm today.</Text>
            <Text>She stepped in something unpleasant.</Text>
        </Message>
        <Message Name="shift.good">
            <Text>She cleaned the building while humming a pleasant tune.</Text>
            <Text>She had a great time working today.</Text>
        </Message>
        <Message Name="shift.neutral">
            <Text>The shift passed uneventfully.</Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/FilmFaceFuck.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FFac">
    <Description>
        She will be used in gag and face-fuck scenes.
    </Description>

    <Performance>
        <Factor Stat="Beauty" Weight="2"/>
        <Factor Stat="Charisma" Weight="1"/>
        <Factor Skill="OralSex" Weight="1"/>
        <Factor Skill="Performance" Weight="2"/>

        <Mod>work.pornstar</Mod>

        <!-- Good -->
        <Trait Name="Deep Throat" Value="80"/> <!-- better ability -->
        <Trait Name="Mind Fucked" Value="60"/> <!-- eager to please -->
        <Trait Name="No Gag Reflex" Value="50"/>
        <Trait Name="Masochist" Value="50"/>
        <Trait Name="Cum Addict" Value="40"/>
        <Trait Name="No Teeth" Value="25"/>    <!-- Lower resistance -->
        <Trait Name="Missing Teeth" Value="25"/>
        <Trait Name="Good Kisser" Value="20"/>
        <Trait Name="Dick-Sucking Lips" Value="20"/>
        <Trait Name="Demon Possessed" Value="20"/> <!-- Wild -->
        <Trait Name="Nimble Tongue" Value="10"/>
        <Trait Name="Pierced Tongue" Value="15"/>
        <Trait Name="Exotic" Value="10"/>
        <Trait Name="Whore" Value="20"/>   <!-- Knows how to work it -->
        <Trait Name="Nymphomaniac" Value="25"/>    <!-- had lots of practice -->
        <Trait Name="Slut" Value="15"/>    <!-- had practice -->
        <Trait Name="Sexy Air" Value="10"/>
        <Trait Name="Open Minded" Value="10"/>
        <Trait Name="Natural Pheromones" Value="5"/>

        <!-- Bad -->
        <Trait Name="Strong Gag Reflex" Value="-20"/>
        <Trait Name="Gag Reflex" Value="-20"/>
        <Trait Name="Clumsy" Value="-25"/>
        <Trait Name="Nervous" Value="-15"/>
    </Performance>

    <Gains XP="10" Skill="3">
        <Skill Name="Performance" Weight="2" Max="66"/>
        <Skill Name="OralSex" Weight="1" Max="75"/>
        <Stat Name="Constitution" Weight="1" Max="33"/>

        <GainTrait Trait="Mind Fucked" Threshold="90" Action="PORNSTAR" Event="2">
            She has been abused so much she is now completely Mind Fucked.
        </GainTrait>
        <GainTrait Trait="Masochist" Threshold="65" Action="SEX">
            ${name} has turned into a Masochist from filming so many BDSM scenes.
        </GainTrait>
        <GainTrait Trait="Porn Star" Threshold="80" Action="PORNSTAR" MinPerformance="200">
            She has performed in enough sex scenes that she has become a well known Porn Star.
        </GainTrait>
        <GainTrait Trait="Iron Will" Threshold="80" Action="SEX" Chance="5">
            Somewhere between having a dick in her throat, balls slapping her eyes and a camera watching her retch,
            ${name} has lost her iron will.
        </GainTrait>
    </Gains>

    <Config PrimaryAction="PORNSTAR" SecondaryAction="SEX" MinimumHealth="25" CanBeForced="1">
        <LustInfluence Amount="15" SkillMin="50" BaseValue="30" Skill="OralSex" />
    </Config>

    <Messages>
        <Message Name="work">
            <Text>${name} was filmed in facefucking scenes.</Text>
            <Text Condition="Mind Fucked">
                Mind fucked ${name} was pleased to be paraded naked in public and tortured and degraded. It is natural.
            </Text>
            <Text Condition="Masochist">
                Masochist ${name} was pleased to be tortured, used and degraded. It is her place.
            </Text>
        </Message>
        <Message Name="crew.refuse.health">
            <Text>
                The crew refused to film a throatjob scene because ${name} is not healthy enough.
                "We are NOT filming snuff".
            </Text>
        </Message>

        <Message Name="work.perfect">
            <Text>
                ${name} knelt in front of him, opened wide, and swallowed down his whole length,
                bouncing back and forward until he came
            </Text>
            <Text>
                ${name} lay on her back on the bed with her head hanging back over the edge.
                Gripping her breasts, he rammed his cock down her throat until cum exploded
            </Text>
            <Text>
                The actor sat on a chair, with ${name} knelt before him. Gripping her head,
                he pulled her onto his cock, rocking her back and forward on his cock until he came
            </Text>
            $[deep down her throat|in her mouth|deep in her stomach].
        </Message>
        <Message Name="work.great">
            <Text>${name} knelt in front of him and sucked his cock down, bouncing back and forward until he came</Text>
            <Text>${name} lay back on the bed with her head over the edge. He fucked her throat until he came</Text>
            <Text>
                The actor sat on a chair, with ${name} before him. Gripping her head,
                he pulled her onto his cock, back and forth until he came
            </Text>
            $[all over her|in her mouth|deep down her throat].
        </Message>
        <Message Name="work.good">
            <Text>${name} knelt down and let him facefuck her until he came</Text>
            <Text>${name} lay on the bed and let him fuck her throat. He carefully facefucked her until he came</Text>
            <Text>The actor pulled ${name}'s head onto his cock, rubbing his cock down her throat until he came</Text>
            $[all over her|in her mouth|deep down her throat].
        </Message>
        <Message Name="work.ok">
            <Text>${name} knelt down and get his cock down her throat. Eventually he came</Text>
            <Text>
                ${name} lay on the bed and tried to take his meat in her throat.
                He facefucked her until he finally came
            </Text>
            <Text>The actor pulled ${name}'s head onto his cock, making her gag, until he came</Text>
            $[in her face|in her mouth|over her face].
        </Message>
        <Message Name="work.bad">
            <Text>
                It was a pretty awkward scene, with the actor not getting much pleasure trying to fuck her throat.
                In the end he gave up and plunged his cock down her throat, making her throw up through her nose,
                as he came in her head.
            </Text>
        </Message>
        <Message Name="work.worst">
            <Text>
                With her continual gagging, retching and vomittig the actor couldn't get any pleasure,
                and ended up wanking over her face.
            </Text>
        </Message>

        <Message Name="disobey.free">
            <Text>${name} angrily refused to be throat-fucked on film today.</Text>
        </Message>
        <Message Name="disobey.slave.nice">
            <Text>
                ${name} angrily refused to be throat-fucked on film today.
                Though she is a slave, she was upset so you allowed her the day off.</Text>
        </Message>
        <Message Name="disobey.slave.neutral">
            <Text>
                ${name} angrily refused to be throat-fucked on film today.
                Amused, you over-ruled her, and gave owner's consent for her. She glared at you as they dragged her away.
            </Text>
        </Message>
        <Message Name="disobey.slave.evil">
            <Text>
                ${name} angrily refused to be throat-fucked on film today.
                Amused, you over-ruled her, and gave owner's consent.
                She made a hell of a fuss, but you knew just the thing to shut her up.
            </Text>
        </Message>

        <Message Name="forced-filming">
            <Text Condition="Performance>100">
                Given ${name}'s rather 'unenthusiastic' performance, the scene turned out decent enough.
            </Text>
            <Text Condition="Performance<125^stat:Spirit<60">
                ${name} is just laying there, totally unresponsive except for a few whimpers and cries.
                Not a good scene.
            </Text>
            <Text Condition="Performance<125^stat:Spirit>=60">
                Despite being tied up, ${name} managed to hurt the other actor. Needless to say, the scene
                turned out rather bad.
            </Text>
            <Text Condition="Performance<50">
                While tying her up made it possible to film this scene, the result looks so bad that maybe you should
                have just sent her to the dungeon instead.
            </Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/FilmMast.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FMst">
    <Description>
        She will perform in a masturbation scene.
    </Description>

    <Performance>
        <Factor Stat="Beauty" Weight="1"/>
        <Factor Stat="Charisma" Weight="2"/>
        <Factor Skill="Performance" Weight="2"/>
        <Factor Skill="Lesbian" Weight="1"/>
        <Mod>work.pornstar</Mod>
    </Performance>

    <Gains XP="10" Skill="3">
        <Skill Name="Performance" Weight="2" Min="25"/>
        <Skill Name="Lesbian" Weight="1" Max="50" Min="20"/>

        <GainTrait Trait="Porn Star" Threshold="70" Action="PORNSTAR">
            She has performed in enough sex scenes that she has become a well known Porn Star.
        </GainTrait>
        <GainTrait Trait="Fake Orgasm Expert" Threshold="50" Action="SEX">
            She has become quite the Faker.
        </GainTrait>

        <LoseTrait Trait="Chaste" Threshold="20" Action="PORNSTAR">
            She has been filmed having sex so often that she is no longer Chaste.
        </LoseTrait>
    </Gains>

    <Config PrimaryAction="PORNSTAR" SecondaryAction="SEX">
        <!-- Not sure which skill to use here -->
        <LustInfluence Amount="25" SkillMin="20" BaseValue="5" Skill="Lesbian" />
    </Config>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as an actress filming Masturbation scenes.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to masturbate on film today.</Text>
        </Message>

        <Message Name="work.perfect">
            <Text>${name} embrassing the entire crew she perfectly pleased her entire body with her hands.</Text>
        </Message>
        <Message Name="work.great">
            <Text>${name} did a great job teasing the cameramage today. She worked her pussy very high for the viewer.</Text>
        </Message>
        <Message Name="work.good">
            <Text>${name} did a good job to day fingering herself. She moaned a name that couldn't be understood.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>${name} did an ok job today. Sadly she was to quick to finish.</Text>
        </Message>
        <Message Name="work.bad">
            <Text>${name} did a bad scene, she was mechanical in all her actions and words.</Text>
        </Message>
        <Message Name="work.worst">
            <Text>${name} made the worst scene EVER.  She didn't even get her pussy wet. She got punished by cleaning the toilet with her own panties.</Text>
        </Message>

    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/FilmFoot.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FFJ">
    <Description>
        She will perform in a foot job scene.
    </Description>

    <Performance>
        <Factor Stat="Charisma" Weight="2"/>
        <Factor Stat="Beauty" Weight="1"/>
        <Factor Skill="Performance" Weight="2"/>
        <Factor Skill="Footjob" Weight="1"/>
        <Mod>work.pornstar</Mod>
    </Performance>

    <Gains XP="15" Skill="3">
        <Skill Name="Performance" Weight="2" Max="75"/>
        <Skill Name="Footjob" Weight="1" Max="75"/>

        <GainTrait Trait="Porn Star" Threshold="70" Action="PORNSTAR">
            She has performed in enough sex scenes that she has become a well known Porn Star.
        </GainTrait>

        <LoseTrait Trait="Chaste" Threshold="20" Action="PORNSTAR">
            She has been filmed having sex so often that she is no longer Chaste.
        </LoseTrait>
    </Gains>

    <Config PrimaryAction="PORNSTAR" SecondaryAction="SEX">
        <LustInfluence Amount="10" SkillMin="20" BaseValue="5" Skill="Footjob" />
    </Config>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as an actress filming foot job scenes.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to use her feet on film today.</Text>
        </Message>

        <Message Name="work.perfect">
            <Text>${name} is TRUELY a Foot Fetish Goddess! Worth every penny.</Text>
        </Message>
        <Message Name="work.great">
            <Text>${name} is a great up and cumming foot fetish actress.</Text>
        </Message>
        <Message Name="work.good">
            <Text>${name} did enjoy using her feet  today.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>${name} did an OK Footjob today. Hopefully she improves in her next scene.</Text>
        </Message>
        <Message Name="work.bad">
            <Text>${name} hated giving a footjob to a creapy actor.</Text>
        </Message>
        <Message Name="work.worst">
            <Text>${name} was visually discusted using her feet. The Director yelled at her for hours.</Text>
        </Message>
    </Messages>
</Job>
