=== crazywm/crazys-wm-mod/Resources/Data/Jobs/job.dtd
<!ELEMENT Job (Description, Performance, Modifiers?, Gains, Config, Messages?)>
<!ATTLIST Job ShortName CDATA #REQUIRED>

<!ELEMENT Description (#PCDATA)>
<!ELEMENT Config ANY>

<!ELEMENT Performance (Factor|Trait|Mod)*>
<!ATTLIST Performance Modifier CDATA #IMPLIED>
<!ELEMENT Factor EMPTY>
<!ATTLIST Factor Skill CDATA #IMPLIED Stat CDATA #IMPLIED Weight CDATA #IMPLIED Min CDATA #IMPLIED Max CDATA #IMPLIED>

<!ELEMENT Gains (GainTrait|LoseTrait|Skill|Stat)*>
<!ATTLIST Gains XP CDATA #IMPLIED Skill CDATA #IMPLIED>
<!ELEMENT GainTrait (#PCDATA)>
<!ATTLIST GainTrait Trait CDATA #REQUIRED Threshold CDATA #REQUIRED Action CDATA #REQUIRED Event CDATA #IMPLIED Chance CDATA #IMPLIED MinPerformance CDATA #IMPLIED>
<!ELEMENT LoseTrait (#PCDATA)>
<!ATTLIST LoseTrait Trait CDATA #REQUIRED Threshold CDATA #REQUIRED Action CDATA #REQUIRED Event CDATA #IMPLIED Chance CDATA #IMPLIED MinPerformance CDATA #IMPLIED>
<!ELEMENT Skill (EMPTY)>
<!ATTLIST Skill Name CDATA #REQUIRED Weight CDATA Min CDATA Max CDATA>
<!ELEMENT Stat (EMPTY)>
<!ATTLIST Stat Name CDATA #REQUIRED Weight CDATA Min CDATA Max CDATA>

<!ELEMENT Messages (Message|Include)*)>
<!ELEMENT Message ((Text|Group)+)>
<!ATTLIST Message Name CDATA #REQUIRED>
<!ELEMENT Text (#PCDATA)>
<!ATTLIST Text Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>
<!ELEMENT Group ((Text|Group)+)>
<!ATTLIST Group Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>

<!ELEMENT Modifiers (Modifier)*>
<!ELEMENT Modifier (Trait)*>
<!ATTLIST Modifier Name CDATA #REQUIRED>
<!ELEMENT Trait (EMPTY)*>
<!ATTLIST Trait Name CDATA #REQUIRED Value CDATA #REQUIRED>

<!ELEMENT Mod (#PCDATA)>
<!ATTLIST Mod Weight CDATA #IMPLIED>

<!ELEMENT Include (#PCDATA)>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/Counselor.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Cnsl">
    <Description>
        She will help girls get over their addictions and problems.
    </Description>

    <Performance>
        <Factor Stat="Intelligence" Weight="1"/>
        <Factor Stat="Confidence" Weight="1"/>
        <Factor Stat="Morality" Weight="1"/>
        <Factor Stat="Charisma" Weight="1"/>
        <Mod>work.counselor</Mod>
    </Performance>

    <Gains XP="5" Skill="2">
        <Skill Name="Service" Weight="1" />
        <Stat Name="Charisma" Weight="1" />
        <GainTrait Trait="Charismatic" Threshold="60" Action="WORKCOUNSELOR">
            Dealing with patients and talking with them about their problems has made ${name} more Charismatic.
        </GainTrait>
        <LoseTrait Trait="Nervous" Threshold="30" Action="WORKCOUNSELOR">
            ${name} seems to finally be getting over her shyness. She's not always so Nervous anymore.
        </LoseTrait>
    </Gains>

    <Messages>
        <Message Name="refuse">
            <Text>${name} refused to counsel anyone.</Text>
        </Message>
        <Message Name="work">
            <Text>${name} counseled patients.</Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/CameraMage.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="CM">
    <Description>
        She will film the scenes. One CameraMage can film at most 3 scenes per week.
    </Description>

    <Performance>
        <Factor Stat="Confidence" Weight="1"/>
        <Factor Stat="Spirit" Weight="1"/>
        <Factor Stat="Agility" Weight="1"/>
        <Factor Skill="Magic" Weight="1"/>
        <Factor Skill="Service" Weight="1"/>
    </Performance>

    <Gains XP="5" Skill="3">
        <Skill Name="Magic" Weight="2" Max="50" />
        <Skill Name="Service" Weight="1" Max="50" />
        <Stat Name="Agility" Weight="1" Max="66" />
        <Stat Name="Confidence" Weight="1" />
    </Gains>

    <Messages>
        <Message Name="no-crew">
            <Text>There was no crew to film the scene, so ${name} took the day off.</Text>
        </Message>
        <Message Name="no-actress">
            <Text>There were no actresses to film, so ${name} took the day off.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work as a camera mage today.</Text>
        </Message>
        <Message Name="work">
            <Text>${name} was assigned to work as a Camera Mage.</Text>
        </Message>
        <Message Name="work.perfect">
            <Text>
                ${name} is a true magician behind the camera.
                She manages to capture every moment perfectly. Future generations of camera mages will
                study her work and use it as reference to aspire to.
            </Text>
        </Message>
        <Message Name="work.great">
            <Text>${name} is a great cinematomancer. Wide angles, close ups, fast movement, she has a spell for each
            situation, and uses them to great artistic effect.</Text>
        </Message>
        <Message Name="work.good">
            <Text>${name} is a great camera mage. Her recording spells work well in most studio conditions, even
            though she still has some difficulties with bad lighting and quick movements. </Text>
        </Message>
        <Message Name="work.ok">
            <Text>${name} did decent camera work today. No artistic masterpiece, to be sure, but the image
            is sharp and steady. </Text>
        </Message>
        <Message Name="work.bad">
            <Text>${name}'s cinematomancy still needs some work. She can produce a stable picture, but
                it often is out of focus and blurry.
            </Text>
        </Message>
        <Message Name="work.worst">
            <Text>${name} is barely able to perform the recording spell. The resulting image is flickering,
            shaky and blurry.</Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/Brewer.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Brwr">
    <Description>
        She will make various beers and wines.
    </Description>

    <Performance>
        <Factor Skill="Brewing" Weight="3"/>
        <Factor Skill="Herbalism" Weight="1"/>
        <Factor Skill="Cooking" Weight="1"/>
        <Factor Stat="Intelligence" Weight="1"/>

        <!-- good traits -->
        <Trait Name="Quick Learner" Value="5"/>
        <Trait Name="Psychic" Value="10"/>
        <Trait Name="Farmers Daughter" Value="10"/>
        <Trait Name="Country Gal" Value="10"/>
        <Trait Name="Mixologist" Value="50"/>

        <!-- bad traits -->
        <Trait Name="Dependant" Value="-50"/> <!-- needs others to do the job -->
        <Trait Name="Clumsy" Value="-20"/> <!-- spills food and breaks things often -->
        <Trait Name="Aggressive" Value="-20"/> <!-- gets mad easy -->
        <Trait Name="Nervous" Value="-30"/> <!-- don't like to be around people -->
        <Trait Name="Meek" Value="-20"/>

        <Trait Name="One Arm" Value="-40"/>
        <Trait Name="One Foot" Value="-20"/>
        <Trait Name="One Hand" Value="-30"/>
        <Trait Name="One Leg" Value="-35"/>
        <Trait Name="No Arms" Value="-125"/>
        <Trait Name="No Feet" Value="-40"/>
        <Trait Name="No Hands" Value="-50"/>
        <Trait Name="No Legs" Value="-75"/>
        <Trait Name="Blind" Value="-30"/>
        <Trait Name="Retarded" Value="-60"/>
        <Trait Name="Smoker" Value="-10"/> <!-- would need smoke breaks -->

        <Trait Name="Alcoholic" Value="-50"/>
        <Trait Name="Fairy Dust Addict" Value="-25"/>
        <Trait Name="Shroud Addict" Value="-25"/>
        <Trait Name="Viras Blood Addict" Value="-25"/>
    </Performance>

    <Gains XP="10" Skill="3">
        <Skill Name="Brewing" Weight="3"/>
        <Skill Name="Herbalism" Weight="1"/>
        <Skill Name="Cooking" Weight="1"/>

        <GainTrait Trait="Chef" Threshold="70" Action="COOKING">
            ${name} has prepared enough food to qualify as a Chef.
        </GainTrait>
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as a brewer on the farm.</Text>
        </Message>
        <Message Name="repair">
            <Text>She spent some of her time repairing the Farm's equipment instead of making new stuff.</Text>
        </Message>
        <Message Name="produce">
            <Text>${name} made:</Text>
        </Message>
        <Include>DefaultPerformanceMessages.xml</Include>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/MarketResearch.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="MktRs">
    <Description>
        She will gather information about the different target groups of your movie studio.
    </Description>

    <Performance>
        <Factor Stat="Charisma" Weight="2"/>
        <Factor Stat="Intelligence" Weight="1" Max="50"/>
    </Performance>

    <Gains XP="5" Skill="3">
        <Stat Name="Charisma" Weight="1" Max="75"/>
        <Stat Name="Intelligence" Weight="1" Max="50"/>
    </Gains>

    <Messages>
        <Message Name="refuse">
            <Text>${name} refused to do Market Research today.</Text>
        </Message>
        <Message Name="work">
            <Text>${name} gathered information about Crossgate's moviegoers today.</Text>
        </Message>

        <Message Name="work.perfect">
            <Text>
                Her charming ways mean that folks really want to tell her about their movie preferences, and
                her sharp mind allows her to put this information to good use. It is as if she were made for this
                job.
            </Text>
        </Message>
        <Message Name="work.great">
            <Text>${name} is a great Market Researcher.</Text>
        </Message>
        <Message Name="work.good">
            <Text>${name} is quite good as a Market Researcher.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>${name} is ok at being a Market Researcher.</Text>
        </Message>
        <Message Name="work.bad">
            <Text>${name} isn't really a good Market Researcher.
            </Text>
        </Message>
        <Message Name="work.worst">
            <Text>${name} is the worst Market Researcher your could ever imagine.</Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/HouseCook.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Hcok">
    <Description>
        She will cook for your house.
    </Description>

    <Performance>
        <Factor Skill="Cooking" Weight="3"/>
        <Factor Skill="Herbalism" Weight="1"/>
        <Factor Skill="Service" Weight="1"/>
        <Factor Stat="Intelligence" Weight="1"/>

        <!-- good traits -->
        <Trait Name="Quick Learner" Value="5"/>
        <Trait Name="Psychic" Value="10"/>
        <Trait Name="Chef" Value="30"/>
        <Trait Name="Mixologist" Value="20"/>  <!-- Good with measures -->

        <!-- bad traits -->
        <Trait Name="Dependent" Value="-50"/> <!-- needs others to do the job -->
        <Trait Name="Clumsy" Value="-20"/> <!-- spills food and breaks things often -->
        <Trait Name="Aggressive" Value="-20"/> <!-- gets mad easy -->
        <Trait Name="Nervous" Value="-20"/> <!-- don't like to be around people -->
        <Trait Name="Meek" Value="-10"/>

        <Trait Name="One Arm" Value="-40"/>
        <Trait Name="One Foot" Value="-20"/>
        <Trait Name="One Hand" Value="-30"/>
        <Trait Name="One Leg" Value="-60"/>
        <Trait Name="No Arms" Value="-125"/>
        <Trait Name="No Feet" Value="-50"/>
        <Trait Name="No Hands" Value="-75"/>
        <Trait Name="No Legs" Value="-40"/>
        <Trait Name="Blind" Value="-30"/>
        <Trait Name="Deaf" Value="-15"/>
        <Trait Name="Retarded" Value="-60"/>
        <Trait Name="Smoker" Value="-10"/> <!-- would need smoke breaks -->

        <Trait Name="Alcoholic" Value="-25"/>
        <Trait Name="Fairy Dust Addict" Value="-25"/>
        <Trait Name="Shroud Addict" Value="-25"/>
        <Trait Name="Viras Blood Addict" Value="-25"/>
    </Performance>

    <Gains XP="20" Skill="3">
        <LoseTrait Trait="Clumsy" Threshold="30" Action="COOKING">
            It took her breaking hundreds of dishes, and just as many reprimands,
            but ${name} has finally stopped being so Clumsy.
        </LoseTrait>
        <Skill Name="Cooking"/>
    </Gains>

    <Config>
        <WageFunction>
            <Point Performance="245" Wages="20" />
            <Point Performance="185" Wages="15" />
            <Point Performance="145" Wages="10" />
            <Point Performance="100" Wages="5" />
            <Point Performance="70" Wages="0" />
            <Point Performance="0" Wages="-15" />
        </WageFunction>
    </Config>

    <Messages>
        <Message Name="work">
            <Text>${name} worked cooking for your House.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to cook for your House.</Text>
        </Message>

        <Message Name="work.perfect">
            <Text>She must be perfect at this.</Text>
        </Message>
        <Message Name="work.great">
            <Text>She's unbelievable at this and is always getting praised by people for her work.</Text>
        </Message>
        <Message Name="work.good">
            <Text>She's good at this job and gets praised by people often.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>She made a few mistakes but overall she is okay at this.</Text>
        </Message>
        <Message Name="work.bad">
            <Text>She was nervous and made a few mistakes. She isn't that good at this.</Text>
        </Message>
        <Message Name="work.worst">
            <Text>She was nervous and constantly making mistakes. She really isn't very good at this job.</Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/Doctor.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Doc">
    <Description>
        She will become a doctor. Doctors earn extra cash from treating locals. (requires at least 1 to perform surgeries)
    </Description>

    <Performance>
        <Factor Skill="Medicine" Weight="2"/>
        <Factor Stat="Intelligence" Weight="1"/>

        <!-- good traits -->
        <Trait Name="Charismatic" Value="20"/>
        <Trait Name="Sexy Air" Value="10"/>
        <Trait Name="Cool Person" Value="10"/>
        <Trait Name="Cute" Value="5"/>
        <Trait Name="Charming" Value="15"/>
        <Trait Name="Nerd" Value="30"/>
        <Trait Name="Quick Learner" Value="10"/>
        <Trait Name="Psychic" Value="20"/> <!-- Don't have to ask "Where does it hurt?" -->
        <Trait Name="Doctor" Value="50"/>
        <Trait Name="Goddess" Value="10"/> <!-- might be able to heal people easier.. they are a goddess after all -->
        <Trait Name="Optimist" Value="10"/>
        <Trait Name="Priestess" Value="10"/>

        <!-- bad traits -->
        <Trait Name="Dependant" Value="-50"/>
        <Trait Name="Clumsy" Value="-20"/>
        <Trait Name="Aggressive" Value="-20"/>
        <Trait Name="Nervous" Value="-50"/>
        <Trait Name="Retarded" Value="-100"/>
        <Trait Name="Meek" Value="-20"/>
        <Trait Name="Mind Fucked" Value="-50"/>
        <Trait Name="Pessimist" Value="-10"/>
        <Trait Name="Sadistic" Value="-20"/>
        <Trait Name="Zombie" Value="-100"/>

        <Trait Name="One Arm" Value="-40"/>
        <Trait Name="One Foot" Value="-40"/>
        <Trait Name="One Hand" Value="-30"/>
        <Trait Name="One Leg" Value="-60"/>
        <Trait Name="No Arms" Value="-150"/>
        <Trait Name="No Feet" Value="-60"/>
        <Trait Name="No Hands" Value="-90"/>
        <Trait Name="No Legs" Value="-150"/>
        <Trait Name="Blind" Value="-75"/>
        <Trait Name="Deaf" Value="-15"/>
        <Trait Name="Retarded" Value="-60"/>
        <Trait Name="Smoker" Value="-10"/> <!-- would need smoke breaks -->

        <Trait Name="Former Addict" Value="-25"/> <!-- not good idea to let former addict around all those drugs -->
        <Trait Name="Alcoholic" Value="-25"/>
        <Trait Name="Fairy Dust Addict" Value="-25"/>
        <Trait Name="Shroud Addict" Value="-25"/>
        <Trait Name="Viras Blood Addict" Value="-25"/>
    </Performance>

    <Gains XP="10" Skill="3">
        <Skill Name="Medicine" Weight="2" />
        <Stat Name="Intelligence" Weight="1" />
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as a Doctor.</Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/Mistress.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Msts">
    <Description>
        She will train the other girls. This will boost the effectiveness of Practice Skills drastically.
    </Description>

    <Performance>
        <Factor Stat="Spirit" Weight="1" />
        <Factor Stat="Charisma" Weight="1" />
        <Factor Stat="Constitution" Weight="1" />
        <Factor Stat="Confidence" Weight="2" />

        <Trait Name="Mute" Value="-20" />
        <Trait Name="Deaf" Value="-10" />
        <Trait Name="Retarded" Value="-100" />
        <Trait Name="Muscular" Value="5" />
        <Trait Name="Giant" Value="5" />
        <Trait Name="Tall" Value="2" />
        <Trait Name="Teacher" Value="15" />
        <Trait Name="Broken Will" Value="-100" />
        <Trait Name="Mind Fucked" Value="-100" />
        <Trait Name="Dependent" Value="-20" />
        <Trait Name="Meek" Value="-20" />
        <Trait Name="Nervous" Value="-10" />
        <Trait Name="Dominatrix" Value="10" />
        <Trait Name="Fragile" Value="-5" />
        <Trait Name="Delicate" Value="-5" />
        <Trait Name="Tough" Value="5" />
        <Trait Name="Charismatic" Value="10" />
        <Trait Name="Noble" Value="5" />
        <Trait Name="Princess" Value="5" />
        <Trait Name="Queen" Value="5" />
    </Performance>

    <Gains XP="15" Skill="3">
        <Stat Name="Spirit" Max="80" />
        <Stat Name="Confidence" Max="80" />
        <!--
        <GainTrait Trait="Teacher" Threshold="50" Action="" />
        -->
    </Gains>

    <Messages>
        <Message Name="refuse">
            <Text>${name} refused to train your other girls.</Text>
        </Message>
        <Message Name="work.normal">
            <Text>
                ${name} spent the ${shift} shift training other girls and generally 'motivating' your slaves.
            </Text>
        </Message>
        <Message Name="work.good">
            <Text>
                ${name} spent the ${shift} shift training other girls and generally 'motivating' your slaves.
                She is an experienced Mistress and can train two girls at the same time.
            </Text>
        </Message>
        <Message Name="slacker">
            <Text>
                She found ${slacker} slacking off instead of working.
                Nothing a few cracks of her whip couldn't solve, though.
            </Text>
        </Message>
    </Messages>
</Job>
