=== crazywm/crazys-wm-mod/Resources/Data/Jobs/job.dtd
<!ELEMENT Job (Description, Performance, Modifiers?, Gains, Config, Messages?)>
<!ATTLIST Job ShortName CDATA #REQUIRED>

<!ELEMENT Description (#PCDATA)>
<!ELEMENT Config ANY>

<!ELEMENT Performance (Factor|Trait|Mod)*>
<!ATTLIST Performance Modifier CDATA #IMPLIED>
<!ELEMENT Factor EMPTY>
<!ATTLIST Factor Skill CDATA #IMPLIED Stat CDATA #IMPLIED Weight CDATA #IMPLIED Min CDATA #IMPLIED Max CDATA #IMPLIED>

<!ELEMENT Gains (GainTrait|LoseTrait|Skill|Stat)*>
<!ATTLIST Gains XP CDATA #IMPLIED Skill CDATA #IMPLIED>
<!ELEMENT GainTrait (#PCDATA)>
<!ATTLIST GainTrait Trait CDATA #REQUIRED Threshold CDATA #REQUIRED Action CDATA #REQUIRED Event CDATA #IMPLIED Chance CDATA #IMPLIED MinPerformance CDATA #IMPLIED>
<!ELEMENT LoseTrait (#PCDATA)>
<!ATTLIST LoseTrait Trait CDATA #REQUIRED Threshold CDATA #REQUIRED Action CDATA #REQUIRED Event CDATA #IMPLIED Chance CDATA #IMPLIED MinPerformance CDATA #IMPLIED>
<!ELEMENT Skill (EMPTY)>
<!ATTLIST Skill Name CDATA #REQUIRED Weight CDATA Min CDATA Max CDATA>
<!ELEMENT Stat (EMPTY)>
<!ATTLIST Stat Name CDATA #REQUIRED Weight CDATA Min CDATA Max CDATA>

<!ELEMENT Messages (Message|Include)*)>
<!ELEMENT Message ((Text|Group)+)>
<!ATTLIST Message Name CDATA #REQUIRED>
<!ELEMENT Text (#PCDATA)>
<!ATTLIST Text Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>
<!ELEMENT Group ((Text|Group)+)>
<!ATTLIST Group Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>

<!ELEMENT Modifiers (Modifier)*>
<!ELEMENT Modifier (Trait)*>
<!ATTLIST Modifier Name CDATA #REQUIRED>
<!ELEMENT Trait (EMPTY)*>
<!ATTLIST Trait Name CDATA #REQUIRED Value CDATA #REQUIRED>

<!ELEMENT Mod (#PCDATA)>
<!ATTLIST Mod Weight CDATA #IMPLIED>

<!ELEMENT Include (#PCDATA)>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/FilmOral.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FOrl">
    <Description>
        She will perform in an oral sex scene.
    </Description>
    <Performance>
        <Factor Stat="Charisma" Weight="2"/>
        <Factor Stat="Beauty" Weight="1"/>
        <Factor Skill="OralSex" Weight="1"/>
        <Factor Skill="Performance" Weight="2"/>

        <Mod>work.pornstar</Mod>

        <!-- Good -->
        <Trait Name="Deep Throat" Value="60"/> <!-- better ability -->
        <Trait Name="No Gag Reflex" Value="40"/>
        <Trait Name="Good Kisser" Value="20"/>
        <Trait Name="Nimble Tongue" Value="20"/>
        <Trait Name="Pierced Tongue" Value="25"/>
        <Trait Name="Dick-Sucking Lips" Value="35"/>
        <Trait Name="Exotic" Value="5"/>
        <Trait Name="Whore" Value="20"/>   <!-- Knows how to work it -->
        <Trait Name="Porn Star" Value="30"/>   <!-- Knows how to work it on film -->
        <Trait Name="No Teeth" Value="15"/>    <!-- no chance of 'accident' -->
        <Trait Name="Missing Teeth" Value="15"/>
        <Trait Name="Nymphomaniac" Value="25"/>    <!-- had lots of practice -->
        <Trait Name="Slut" Value="15"/>    <!-- had practice -->
        <Trait Name="Cum Addict" Value="30"/>  <!-- eager to please -->
        <Trait Name="Mind Fucked" Value="25"/> <!-- eager to please -->
        <Trait Name="Sexy Air" Value="10"/>
        <Trait Name="Open Minded" Value="10"/>
        <Trait Name="Natural Pheromones" Value="5"/>


        <!-- Bad -->
        <Trait Name="Strong Gag Reflex" Value="-40"/>
        <Trait Name="Gag Reflex" Value="-20"/>
        <Trait Name="Clumsy" Value="-25"/>
    </Performance>

    <Gains XP="10" Skill="3">
        <Skill Name="Performance" Weight="2" Max="75"/>
        <Skill Name="OralSex" Weight="1" Max="50"/>

        <GainTrait Trait="Porn Star" Threshold="70" Action="PORNSTAR">
            She has performed in enough sex scenes that she has become a well known Porn Star.
        </GainTrait>

        <LoseTrait Trait="Chaste" Threshold="20" Action="PORNSTAR">
            She has been filmed having sex so often that she is no longer Chaste.
        </LoseTrait>
    </Gains>

    <Config PrimaryAction="PORNSTAR" SecondaryAction="SEX">
        <LustInfluence Amount="15" SkillMin="25" BaseValue="10" Skill="OralSex" />
    </Config>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as an actress filming oral scenes.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to give head on film today.</Text>
        </Message>
        <Message Name="work.perfect">
            <Text>
            The lucky guy came uncontrollably, damn near passing out in pleasure as ${name} expertly sucked him dry.
            She savoured the cum in her mouth, rolling it around her lips and tongue before finally swallowing it down.
            </Text>
        </Message>
        <Message Name="work.great">
            ${name} sucked off her man like a pro - not once breaking eye-contact - and was rewarded with
            <Text Condition="Cum Addict" Priority="1">
                a mouthful of semen. She kept her lips clamped to his cock to the last,
                thirstily swallowing down every drop of hot cum.
            </Text>
            <Text>
                a mouthful of semen. She kept her lips clamped to his cock to the last,
                thirstily swallowing down every drop of hot cum.
            </Text>
            <Text>
                an explosion of cum in her face. As she licked his penis clean,
                she rubbed cum around her skin and licked it off her fingers.
            </Text>
        </Message>
        <Message Name="work.good">
            <Text>${name} gave a fairly pleasant blowjob, and ended up glazed in hot cum.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>${name} gave a passable blowjob, but in the end the actor had to finish himself off, splatting cum on her face.</Text>
        </Message>
        <Message Name="work.bad">
            <Text>
                It was a pretty awkward and uncomfortable scene,
                with the actor not getting any kind of pleasure from her clumsy, toothy attempts.
                In the end he gave up and simply wanked in her face, but even then she dodged at the last moment,
                ruining that scene too.
            </Text>
        </Message>
        <Message Name="work.worst">
            <Text>
                After the fourth time she 'snagged' the actor on her tooth, he cursed and stormed off set.
                Your goons saved the day by pinning her down wanking on her face one-by-one.
                Overall it's a terrible scene.
            </Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/Fluffer.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Fluf">
    <Description>
        She will keep the porn stars aroused.
    </Description>

    <Performance>
        <Factor Stat="Beauty" Weight="1"/>
        <Factor Skill="OralSex" Weight="1"/>
        <Factor Skill="Service" Weight="1"/>
    </Performance>

    <Gains XP="15" Skill="1">
        <Skill Name="OralSex" Weight="1" />
        <Skill Name="Service" Weight="1" />
    </Gains>

    <Messages>
        <Message Name="no-crew">
            <Text>There was no crew to film the scene, so ${name} took the day off.</Text>
        </Message>
        <Message Name="no-actress">
            <Text>There were no actresses to film, so ${name} took the day off.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work as a fluffer today.</Text>
        </Message>
        <Message Name="work">
            <Text>${name} worked as a fluffer.</Text>
        </Message>
        <Message Name="work.perfect">
            <Text>
                She was so skillful in keeping the actors aroused that your camera mage decided to film some of her work
                too. This will be a great after-credits shot.
            </Text>
        </Message>
        <Message Name="work.great">
            <Text>
                Who needs blue pills and aphrodisiacs when you have ${name}. She is great at keeping the actors ready to
                work.
            </Text>
        </Message>
        <Message Name="work.good">
            <Text>
                She did a good job of keeping the actors aroused.
            </Text>
        </Message>
        <Message Name="work.ok">
            <Text>
                She does a decent job of keeping the actors ready.
            </Text>
        </Message>
        <Message Name="work.bad">
            <Text>
                She is supposed to keep the actors aroused, but her attempts left them amused at best.
            </Text>
        </Message>
        <Message Name="work.worst">
            <Text>
                Her performance on set has earned her the nickname "The Limper". This has nothing to do with the way she
                walks.
            </Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/Blacksmith.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Bksm">
    <Description>
        She will make weapons and armor.
    </Description>

    <Performance>
        <Factor Skill="Crafting" Weight="2"/>
        <Factor Stat="Strength" Weight="2"/>
        <Factor Skill="Combat" Weight="1"/>
        <Factor Skill="Magic" Weight="1"/>
        <Factor Stat="Intelligence" Weight="1"/>
        <Factor Stat="Constitution" Weight=""/>
    </Performance>

    <Gains XP="10" Skill="3">
        <Skill Name="Crafting" Weight="2" />
        <Stat Name="Strength" Weight="2" />
        <Stat Name="Constitution" Weight="2" />
        <Skill Name="Combat" Weight="1" />
        <Skill Name="Magic" Weight="1" />
        <GainTrait Trait="Tough" Threshold="50" Action="MAKEITEMS">
            Working in the heat of the forge has made ${name} rather Tough.
        </GainTrait>
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as a blacksmith at the arena.</Text>
        </Message>
        <Message Name="repair">
            <Text>She spent some of her time repairing the Arena's equipment instead of making new stuff.</Text>
        </Message>
        <Message Name="produce">
            <Text>${name} made:</Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/CleanCentre.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="ClnC">
    <Description>
        She will clean the centre.
    </Description>

    <Performance>
        <Factor Skill="Service" Weight="3"/>
        <Factor Stat="Obedience" Weight="1"/>
        <Factor Stat="Morality" Weight="1"/>
        <Factor Stat="Agility" Weight="1"/>

        <Mod>work.cleaning</Mod>
    </Performance>

    <Messages>
        <Message Name="work">
            <Text>${name} worked cleaning the Centre.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to clean the Centre.</Text>
        </Message>
        <Message Name="shift.bad">
            <Text>She spilled a bucket of something unpleasant all over herself.</Text>
            <Text>She did not like cleaning the Centre today.</Text>
        </Message>
        <Message Name="shift.good">
            <Text>She cleaned the building while humming a pleasant tune.</Text>
            <Text>She had a great time working today.</Text>
        </Message>
        <Message Name="shift.neutral">
            <Text>The shift passed uneventfully.</Text>
        </Message>

        <Message Name="event.nap">
            <Text Updates="Image='REST'">${name} finished her cleaning early, so she took nap.</Text>
        </Message>

        <Message Name="event.bath">
            <Text Updates="Image='BATH'">${name} finished her cleaning early, so took a long bath to clean herself off.</Text>
        </Message>

        <Message Name="event.play">
            <Text>${name} finished her cleaning early, so she played with the children a bit.</Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/Director.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="CM">
    <Description>
        She will direct the scenes. One Director can film at most 3 scenes per week.
    </Description>

    <Performance>
        <Factor Stat="Confidence" Weight="1"/>
        <Factor Stat="Spirit" Weight="1"/>
        <Factor Stat="Intelligence" Weight="1"/>
        <Factor Stat="Charisma" Weight="1"/>
    </Performance>

    <Gains XP="10" Skill="2">
        <Stat Name="Intelligence" Weight="1" Max="50" />
        <Stat Name="Charisma" Weight="1" Max="50"/>
        <Stat Name="Confidence" Weight="1" Min="20" />
    </Gains>

    <Messages>
        <Message Name="no-crew">
            <Text>There was no crew to film the scene, so ${name} took the day off.</Text>
        </Message>
        <Message Name="no-actress">
            <Text>There were no actresses to film, so ${name} took the day off.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work as a Director today.</Text>
        </Message>
        <Message Name="work">
            <Text>${name} directed the filming of some scenes today.</Text>
        </Message>
        <Message Name="work.perfect">
            <Text>
                ${name} is an excellent Director. Not only is she a great cinematographer, but she also helped the
                actress improve her performance.
            </Text>
        </Message>
        <Message Name="work.great">
            <Text>${name} is a great Director.</Text>
        </Message>
        <Message Name="work.good">
            <Text>${name} is quite good as a Director.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>${name} did an ok job directing scenes today. </Text>
        </Message>
        <Message Name="work.bad">
            <Text>${name} isn't really a good Director.
            </Text>
        </Message>
        <Message Name="work.worst">
            <Text>${name} was supposed to be directing some scenes today, but really, all she did was
            confuse the studio crew with contradictory instructions.</Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/Milker.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Mlkr">
    <Description>
        She will milk the various animals and girls you own.
    </Description>

    <Performance>
        <Factor Skill="AnimalHandling" Weight="3"/>
        <Factor Skill="Handjob" Weight="3"/>
        <Factor Stat="Intelligence" Weight="2"/>
        <Factor Skill="Farming" Weight="2" />

        <!-- good traits -->
        <Trait Name="Quick Learner" Value="5"/>
        <Trait Name="Psychic" Value="10"/>
        <Trait Name="Farmers Daughter" Value="30"/>
        <Trait Name="Country Gal" Value="10"/>

        <!-- bad traits -->
        <Trait Name="Dependant" Value="-50"/> <!-- needs others to do the job -->
        <Trait Name="Clumsy" Value="-20"/> <!-- spills food and breaks things often -->
        <Trait Name="Aggressive" Value="-20"/> <!-- gets mad easy -->
        <Trait Name="Nervous" Value="-30"/> <!-- don't like to be around people -->
        <Trait Name="Meek" Value="-20"/>

        <Trait Name="One Arm" Value="-40"/>
        <Trait Name="One Foot" Value="-40"/>
        <Trait Name="One Hand" Value="-30"/>
        <Trait Name="One Leg" Value="-60"/>
        <Trait Name="No Arms" Value="-125"/>
        <Trait Name="No Feet" Value="-60"/>
        <Trait Name="No Hands" Value="-50"/>
        <Trait Name="No Legs" Value="-100"/>
        <Trait Name="Blind" Value="-30"/>
        <Trait Name="Deaf" Value="-15"/>
        <Trait Name="Retarded" Value="-60"/>
        <Trait Name="Smoker" Value="-10"/> <!-- would need smoke breaks -->

        <Trait Name="Alcoholic" Value="-25"/>
        <Trait Name="Fairy Dust Addict" Value="-25"/>
        <Trait Name="Shroud Addict" Value="-25"/>
        <Trait Name="Viras Blood Addict" Value="-25"/>
    </Performance>

    <Gains XP="10" Skill="3">
        <Skill Name="AnimalHandling"/>
        <Skill Name="Handjob"/>
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as a milker on the farm.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work during the ${shift} shift.</Text>
        </Message>

        <Message Name="work.perfect">
            <Text>Her milk bucket practically fills itself as she walks down the rows of cows.</Text>
        </Message>
        <Message Name="work.great">
            <Text>Her hands moved like lightning as she gracefully milks the cows teats.</Text>
        </Message>
        <Message Name="work.good">
            <Text>She knows exactly when the cows are ready to be milked and how to best milk them.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>She can milk the cows without spilling much.</Text>
        </Message>
        <Message Name="work.bad">
            <Text>She isn't very good at aiming the teats into the bucket.</Text>
        </Message>
        <Message Name="work.worst">
            <Text>She can't seem to get the hang of this.</Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/FilmHand.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FHJ">
    <Description>
        She will perform in a hand job scene.
    </Description>
    <Performance>
        <Factor Stat="Beauty" Weight="1"/>
        <Factor Stat="Charisma" Weight="2"/>
        <Factor Skill="Performance" Weight="2"/>
        <Factor Skill="Handjob" Weight="1"/>

        <Mod>work.pornstar</Mod>
        <Trait Name="Lesbian" Value="-15" />
        <Trait Name="Clumsy" Value="-5" />
    </Performance>

    <Gains XP="15" Skill="3">
        <Skill Name="Performance" Weight="2" Max="75"/>
        <Skill Name="Handjob" Weight="1" Max="50"/>

        <GainTrait Trait="Porn Star" Threshold="70" Action="PORNSTAR">
            She has performed in enough sex scenes that she has become a well known Porn Star.
        </GainTrait>

        <LoseTrait Trait="Chaste" Threshold="20" Action="PORNSTAR">
            She has been filmed having sex so often that she is no longer Chaste.
        </LoseTrait>
    </Gains>

    <Config PrimaryAction="PORNSTAR" SecondaryAction="SEX">
        <LustInfluence Amount="10" SkillMin="20" BaseValue="5" Skill="Handjob" />
    </Config>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as an actress filming handjob scenes.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to film a handjob scene today.</Text>
        </Message>


        <Message Name="work.perfect">
            <Text>${name} expertly worked his cock and balls. She almost worshipped it!</Text>
            <Text Condition="One Arm|One Hand">
                ${name} may have only one hand, but she sure knows how to use it.
            </Text>
        </Message>

        <Message Name="work.great">
            <Text>${name} loved giving him a great handjob.</Text>
        </Message>

        <Message Name="work.good">
            <Text>${name} enjoyed tickling him a bit while she gave a decent handjob.</Text>
            <Text Condition="Lesbian">
                ${name} is a decent actress, so despite her personal aversion, she managed to make a good handjob scene.
            </Text>
        </Message>

        <Message Name="work.ok">
            <Text>${name} was ok with the handjob today. She almost wants to do other scenes.</Text>
            <Text Condition="Lesbian">
                ${name}'s handjob was ok, considering that she prefers pussy over cock.
            </Text>
        </Message>

        <Message Name="work.bad">
            <Text>${name} sucked doing the handjob, she was like a drone.</Text>
            <Text Condition="Lesbian">
                ${name} performed a very lacklustre handjob. Maybe it is because she herself has no interest in cock.
            </Text>

            <Text Condition="stat:Beauty>80|Great Figure|Hourglass Figure">
                The Director instructed the Camera Mage to focus more on her figure than on the action. But even with
                clever editing, the scene will be bad.
            </Text>
        </Message>

        <Message Name="work.worst">
            <Text>${name} was the worst actress the Director ever saw. She might be better at behind the scenes jobs.</Text>
            <Text Condition="Lesbian">
                With her dislike of $[cock][dick][penises] so clearly written on her face, ${name} really is unsuited for a handjob scene.
            </Text>
            <Text Condition="One Arm|One Hand">
                One-handed ${name}'s attempts at a handjob succeeded in keeping you crew entertained, but will probably
                only make the blooper reel of your next movie.
            </Text>
        </Message>

        <Message Name="post-work-event">
            <Text Condition="Dick-Sucking Lips ^ Performance < 125" Chance="50">
                With those lips of hers, maybe you should have instructed her to to a blowjob scene.
            </Text>
            <Text Condition="Porn Star ^ Performance < 125" Chance="50">
                From a Porn Star as experienced as ${name} you would have expected better results.
            </Text>
            <Text Condition="skill:Handjob > 80 ^ Performance < 125" Chance="50">
                Even though it doesn't really show on film, ${name}'s costar swears that this was one of the best
                handjobs he's ever had.
            </Text>
        </Message>
    </Messages>
</Job>

=== crazywm/crazys-wm-mod/Resources/Data/Jobs/PeepShow.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Peep">
    <Description>
        She will let people watch her change and maybe more...
    </Description>

    <Performance>
        <!-- intel and agility for smarts and speed to cheat; cust service, performance to bluff/cheat, and a bit of magic for 'luck'-->
        <Factor Stat="Charisma" Weight="1"/>
        <Factor Stat="Beauty" Weight="1"/>
        <Factor Skill="Strip" Weight="1"/>
        <Factor Skill="Performance" Weight="1"/>
        <!-- TODO malus for pregnant -->
        <Mod>work.peepshow</Mod>
    </Performance>

    <Gains XP="15" Skill="3">
        <Skill Name="Strip" Weight="1" Max="50" />
        <Skill Name="Performance" Weight="1" Max="50"/>
        <LoseTrait Trait="Nervous" Threshold="30" Action="WORKSTRIP">
            ${name} has had so many people see her naked she is no longer nervous about anything.
        </LoseTrait>
    </Gains>

    <Messages>
        <Message Name="refuse">
            <Text>${name} refused to be in your brothel's peep show to${shift}</Text>
        </Message>
        <Message Name="work">
            <Text>${name} let the customers watch her get naked.</Text>
        </Message>

        <Message Name="work.perfect">
            She must be the perfect teaser she never goes to fast but never to slow, she knows just when to do things. The customers can't get enough of her.

            <Text>
                Knowing every trick in the book and not hesitating to use them, she makes a lot of money today.
            </Text>
            <Text>
                She is just a gold mine.
            </Text>
            <Text>
                She certainly knows how to sell the show. After hours of teasing she finally gets naked.
            </Text>
            <Text>
                ${name} was requested by name by a single customer.
                He paid double of her daily earnings for the privilege of getting an exclusive performance.
            </Text>
            <Text>
                ${name} is performing today. Like always the cleaning crew have a lot of work after her shows.
            </Text>
        </Message>

        <Message Name="work.great">
            She is unbelievable at this and is always finding new ways of pleasing the customers.

            <Text>
                She is really good at this, knowing how to tease customers into staying and paying for hours.
            </Text>
            <Text>
                ${name} swinging her boobs and ass in a very sexual way.
                As a result causing heavy breathing from the booths.
            </Text>
            <Text>
                Her body movement is flawless and very sensual, earning a nice sum today.
            </Text>
            <Text>
                ${name} gave a very good performance, making her clients very satisfied with the time they spent here.
            </Text>
            <Text>
                ${name} was requested by name by a group of customers.
                She gave them a special performance for a really high price.
            </Text>
        </Message>

        <Message Name="work.good">
            She's good at this job and knows a few tricks to drive the customers wild.

            <Text>
                She has a good body and sense of rhythm,
                but she strips too fast, so she makes less money from today performance.
            </Text>
            <Text>
                She makes the mistake of getting naked too fast, ending the show prematurely.
            </Text>
            <Text>
                She certainly has the skills for this job, but with more work she will get even better.
            </Text>
            <Text>
                ${name} comes on stage with some 'toys' that she uses to prolong her performance.
            </Text>
            <Text>
                Having confidence in her skills, ${name} gives a very good performance.
            </Text>
        </Message>

        <Message Name="work.ok">
            She made a few mistakes but overall she is okay at this.

            <Text>
                ${name} can strip and people come here to see her do that but there is nothing extraordinary in her performance.
            </Text>
            <Text>
                Pretty boring show, But at least she gets naked all the way through.
            </Text>
            <Text>
                Having stage fright, her movement seems mechanical, leaving paying customers unsatisfied.
            </Text>
            <Text>
                Not too confident in herself, ${name}'s tense performance rubs off on the customers.
            </Text>
            <Text>
                She did good today. With improving her skills, ${name} could become one of the best.
            </Text>
        </Message>

        <Message Name="work.bad">
            She was nervous and made a few mistakes. She isn't that good at this.

            <Text>
                When it was time for ${name} to take off her panties,
                she collapsed on the floor covering her breasts and crying.
            </Text>
            <Text>
                Not being able to unbuckle her fancy bra, she struggled for minutes.
                Some of the customers left demanding their money back.
            </Text>
            <Text>
                She gets naked but in a boring and not exciting way.
            </Text>
            <Text>
                Trying a more advanced pose, she hurts herself, falling painfully on the floor.
            </Text>
            <Text>
                ${name} definitely tries to give a good performance, but having only good will isn't enough.
            </Text>
        </Message>

        <Message Name="work.worst">
            She was nervous and constantly making mistakes. She really isn't very good at this job.

            <Text>
                She is awful at this job. Her stage movement and striptease are lifeless.
            </Text>
            <Text>
                Her stripping ability could be compared to getting undressed before a shower.
            </Text>
            <Text>
                Her show was so bad, that you could swear you heard snoring from one booth.
            </Text>
            <Text>
                When trying to take off her t-shirt, ${name}'s head got stuck for minutes.
            </Text>
            <Text>
                Trying to give her best, ${name} gave a poor performance.
            </Text>
        </Message>

    </Messages>
</Job>
